[build]
  base = "/"
  command = "npm run build && npm run postbuild"
  publish = "dist"
  environment = "production"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  status = 200
